### ISSUE TITLE
Failed to find license on CLion 2021.3 RC

### ISSUE THREAD

**Issue by rez23** [ArtsiomCh/CMake#29] opened 2021-11-19 22:14 UTC
Hi, CMake plus is unable to find license on CLion 2021.3. So is not usable.

**Comment by objectx** [comment] 2021-11-29 13:47
Me too 😢 
```
CLion 2021.3 RC2
Build #CL-213.5744.190, built on November 24, 2021
Licensed to Masashi Fujita
Subscription is active until November 28, 2022.
Runtime version: 11.0.13+7-b1751.19 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 10000M
Cores: 20
Registry:
    run.processes.with.pty=TRUE
    ide.mac.transparentTitleBarAppearance=false
    debugger.valueTooltipAutoShowOnSelection=true
    ide.experimental.ui.toolwindow.stripes=true
    ide.tooltip.initialDelay=312
    ide.balloon.shadow.size=0
    clang.parameter.info=true

Non-Bundled Plugins:
    pw.unbear.ijplug (1.0.0)
    org.toml.lang (213.5744.224)
    org.jetbrains.plugins.rest (213.5744.190)
    org.jetbrains.plugins.go-template (213.5744.190)
    org.editorconfig.editorconfigjetbrains (213.5744.121)
    org.antlr.intellij.plugin (1.17)
    net.vektah.codeglance (1.5.4)
    com.paperetto.dash (3.3)
    com.github.leomillon.uuidgenerator (4.5.1)
    com.draculatheme.idea (1.3.3)
    Key Promoter X (2021.3)
    com.chrisrm.idea.MaterialThemeUI (6.10.1)
    zielu.gittoolbox (212.8.2)
    mobi.hsz.idea.gitignore (4.3.0)
    com.mallowigi (50.2.0)
    org.rust.lang (0.4.160.4261-213)
    com.jfrog.conan.clion (1.2.0)
    artsiomch.cmake (213.0.1)
    artsiomch.cmake.plus (213.0.1)
```
<img width="622" alt="image" src="https://user-images.githubusercontent.com/1112949/143878880-9cf00019-0e96-4dec-b2dc-534870907690.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/1112949/143878931-a11c8995-9643-4e47-8cb3-08d7022469bb.png">

**Comment by csitarichie** [comment] 2021-11-29 17:10
I have the same issue :(

**Comment by ArtsiomCh** [comment] 2021-12-02 12:19
fixed at 213.1.2 version(should be available within few hours). Sorry for that folks... :-/

**Comment by ArtsiomCh** [comment] 2021-12-02 12:41
For some reason notifications from GitHub was disabled :(
So if I not responding withing 48 hours here, please try to ping me directly to email or whenever you can find my contacts.
Sorry again, that should be fixed way before...

**Comment by objectx** [comment] 2021-12-03 08:41
At this time, 213.1.2 is not yet available 😢

**Comment by ArtsiomCh** [comment] 2021-12-03 10:02
Just approved by Jetbrains few minutes ago, please try to check again.

**Comment by objectx** [comment] 2021-12-03 12:25
@ArtsiomCh My license is correctly identified now. Thanks!

\# I've switched my license from monthly billing to annual 😉

**Comment by ajakhotia** [comment] 2021-12-04 12:59
YouTrack ticket for the same issue for reference:
https://youtrack.jetbrains.com/issue/CPP-27586

**Comment by ajakhotia** [comment] 2021-12-04 13:22
I still see a licence not found balloon during the launch of my IDE. I am using an annual license. The Help->Register dialog box reports that the license is active. I am unable to use go-to definitions feature  of the plugin. I have double checked that I am on v213.1.2 of the plugin.

**Comment by ArtsiomCh** [comment] 2021-12-04 18:56
Found some changes made by Jetbrains in license check process if licensed via ticket obtained from JetBrains Floating License Server. Please let me know if that's your case?
Also try please [213.1.3](https://drive.google.com/file/d/1Uh63Sf0U_F9hA0_DCceE8WpfNxId8DKc/view?usp=sharing) with fix for such cases by manually installing it from the disk:
![image](https://user-images.githubusercontent.com/14268320/144721312-0bfdf9e1-a8e2-4d25-b694-697825b8b951.png)

**Comment by riggs** [comment] 2021-12-06 23:27
I get the same error even with 213.1.3

I doubt it's relevant, but I actually just purchased the license about 41 hours ago.

**Comment by ArtsiomCh** [comment] 2021-12-07 20:24
@riggs please confirm if you see "CMake Plus plugin License not found. Plugin functionality will be disabled." notification on Ide startup? Do you use Clion 2021.3?
Also check please at Help-Register if your license is identified by Ide? Also check at Settings-Plugins that Cmake Plus is enabled and marked as 'Purchased' ?

@ajakhotia please let me know if 213.1.3 fixed your problem with license?

**Comment by riggs** [comment] 2021-12-07 20:31
Yes, I see the same error at startup. I'm on CLion 2012.3, Build #CL-213.5744.254 (MacOS 12.0.1, M1 MBP). The plugin is marked as Purchased and Enabled.

I also have CLion installed and running via the Toolbox app.

**Comment by ArtsiomCh** [comment] 2021-12-07 21:42
@riggs Ok, let try to debug it. 

- Please install next version with excessive logging: [213.1.3-license-check-log1](https://drive.google.com/file/d/1nudgeS8vKb7IzAkVYToUiq5n3l91YBQm/view?usp=sharing)
- Then restart IDE. Get that error message.
- Then find [idea.log](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) file and send it to me **privately** (as It might contain some sensitive information like your PC name) to achapialiou@gmail.com.

**Comment by riggs** [comment] 2021-12-08 00:36
Sent, and I'm seeing a particularly suspicious line in the logs:
`INFO -   com.cmakeplugin.CheckLicense - cstamp is NULL`

**Comment by ArtsiomCh** [comment] 2021-12-08 19:17
@riggs the only way I can reproduce your situation is absence of plugin license at Help-Register:
![image](https://user-images.githubusercontent.com/14268320/145269233-8dcb0b71-5dc0-43a1-8734-db22185bf1ad.png)
Please make sure you activated your license there:
![image](https://user-images.githubusercontent.com/14268320/145267577-e677630b-ba64-4577-8bc6-2e564ae52fb7.png)
Also sometimes CLion doesn't recognize license right away and IDE restart is needed.

Please try to check(activate it) and let me know if you still getting that "CMake Plus plugin License not found. Plugin functionality will be disabled." message even when activation looks like on second screenshot above.

**Comment by riggs** [comment] 2021-12-08 19:48
I've tried many different combinations of removing, re-activating, & restarting CLion and still get the message about the plugin not finding the license.

**Comment by riggs** [comment] 2021-12-08 19:52
Even after I remove the license and restart CLion, the 'register' pane picks it up and shows the license as registered to my account.

**Comment by riggs** [comment] 2021-12-08 20:00
I just downloaded the license key from the JB website and used to to activate manually and still get the pop-up about the plugin being disabled.

**Comment by ArtsiomCh** [comment] 2021-12-08 20:17
Ok, that become more interesting then :) 
Have some ideas to try, will keep you updated.

**Comment by ArtsiomCh** [comment] 2021-12-08 20:24
@riggs could you please try to install previous CLion 2021.2 (probably you can activate it with the same license you use for Clion 2021.3 or just start 30 days trial). 
Then install 213.1.3 Cmake Plus (together with CMake Simple Highlighter) on it and try to activate plugin there. If not succeed - try 212.0.1 version too.

**Comment by ArtsiomCh** [comment] 2021-12-08 20:37
@riggs and on Clion 2021.3 please try [213.1.3-license-check-log2](https://drive.google.com/file/d/1hFM3wRoyV8tioNCUqU4Vf-JOXwz00KiC/view?usp=sharing)

- Restart Clion after install
- Try to open few projects (no matter what, cmake files presents is not required)
- Collect the log and send it to me again, please

PS I have felling Jetbrains team will be involved soon in that investigation ;)

**Comment by riggs** [comment] 2021-12-10 00:33
`cstamp` managed to find the key this time. No popup. (Still on latest CLion)

**Comment by ajakhotia** [comment] 2021-12-10 10:13
@ArtsiomCh: Hi, apologies for late responses. I still see the issue with plugin version 213.1.3. I additionally also tried the 213.1.3-license-check-log1 and 213.1.3-license-check-log2 with the latest Clion version and have the same observations as @riggs.

**Comment by ArtsiomCh** [comment] 2021-12-10 11:13
@riggs @ajakhotia Sounds like we found the root cause! Just to clarify, you don't see _license check failed_ message anymore with 213.1.3-license-check-log2, right? **And** functionality of Cmake Plus plugin works: docs for commands, structure view, var references, etc, correct?
PS @ajakhotia are on Apple M1 chip as well? I have feeling the issue is related to that somehow. It's looks very like race condition.

**Comment by ajakhotia** [comment] 2021-12-10 11:30
@ArtsiomCh: Yes, that is correct. I do not see license check failed message and the plugin 213.1.3-license-check-log2 works.

No, I am not on Apple M1 chip. I am using an Intel i9 processor.

**Comment by ArtsiomCh** [comment] 2021-12-10 13:03
Great. Stay on 213.1.3-license-check-log2 then. I'll release 213.1.4 with that fix soon.

**Comment by ArtsiomCh** [comment] 2021-12-11 16:08
213.1.4 uploaded. Should be available within few days.
Thanks everyone for help in resolving that issue!

**Closed as completed by ArtsiomCh** 2021-12-11 16:08 UTC

**Comment by ajakhotia** [comment] 2021-12-12 12:57
Thank you for the quick turn-around. 😄
